name: newsapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  webview_flutter: ^4.13.0
  http: ^1.4.0
  cached_network_image: ^3.4.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
